os: linux
dist: xenial
language: python
sudo: false

install:
  - pip install pytest
  - pip install findit
  - pip install .

matrix:
  include:
  - python: "2.7"
    env: TEST_CASE=test_client.py
  - python: "3.5"
    env: TEST_CASE=test_standard.py
  - python: "3.6"
    env: TEST_CASE=test_standard.py
  - python: "3.7"
    env: TEST_CASE=test_standard.py

script:
  - pytest tests/$TEST_CASE
