os: linux
dist: xenial
language: python
python:
#  - "2.7"
#  - "3.5"
  - "3.6"
  - "3.7"
sudo: false

install:
  - pip install pytest pytest-cov codecov
  - pip install findit
  - pip install .

script:
  - pytest tests/test_client.py --cov=./
  - pip install opencv-python
  - pytest tests/test_standard.py --cov=./

after_success:
  - codecov