os: linux
dist: xenial
language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pytest
  - pip install findit
  - pip install .

script:
  - pytest tests/
